feat: Bump mixin dashboards
Also refactor mixins to update build files.
Add ci

diff --git a/celery-mixin/Makefile b/celery-mixin/Makefile
--- a/celery-mixin/Makefile
+++ b/celery-mixin/Makefile
@@ -1,28 +1,100 @@
-JSONNET_FMT := jsonnetfmt -n 2 --max-blank-lines 2 --string-style s --comment-style s
+BIN_DIR ?= $(shell pwd)/tmp/bin
 
-all: fmt prometheus-alerts.yaml dashboards_out lint
+JSONNET_VENDOR=vendor
+GRAFANA_DASHBOARD_LINTER_BIN=$(BIN_DIR)/dashboard-linter
+JB_BIN=$(BIN_DIR)/jb
+JSONNET_BIN=$(BIN_DIR)/jsonnet
+JSONNETLINT_BIN=$(BIN_DIR)/jsonnet-lint
+JSONNETFMT_BIN=$(BIN_DIR)/jsonnetfmt
+MD_FILES = $(shell find . \( -type d -name '.vale' -o -type d -name 'vendor' \) -prune -o -type f -name "*.md" -print)
+MARKDOWNFMT_BIN=$(BIN_DIR)/markdownfmt
+VALE_BIN=$(BIN_DIR)/vale
+PROMTOOL_BIN=$(BIN_DIR)/promtool
+PINT_BIN=$(BIN_DIR)/pint
+TOOLING=$(JB_BIN) $(JSONNETLINT_BIN) $(JSONNET_BIN) $(JSONNETFMT_BIN) $(PROMTOOL_BIN) $(GRAFANA_DASHBOARD_LINTER_BIN) $(MARKDOWNFMT_BIN) $(VALE_BIN) $(PINT_BIN)
+JSONNETFMT_ARGS=-n 2 --max-blank-lines 2 --string-style s --comment-style s
+SRC_DIR ?=dashboards
+OUT_DIR ?=dashboards_out
 
-fmt:
-	find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
-		xargs -n 1 -- $(JSONNET_FMT) -i
+.PHONY: all
+all: fmt generate lint test
 
-prometheus-alerts.yaml: mixin.libsonnet config.libsonnet $(wildcard alerts/*)
-	jsonnet -S alerts.jsonnet > $@
+.PHONY: generate
+generate: prometheus_alerts.yaml prometheus_rules.yaml $(OUT_DIR)
 
-dashboards_out: mixin.libsonnet config.libsonnet $(wildcard dashboards/*)
-	@mkdir -p dashboards_out
-	jsonnet -J vendor -m dashboards_out dashboards.jsonnet
+$(JSONNET_VENDOR): $(JB_BIN) jsonnetfile.json
+	$(JB_BIN) install
 
-lint: prometheus-alerts.yaml
-	find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
-		while read f; do \
-			$(JSONNET_FMT) "$$f" | diff -u "$$f" -; \
-		done
+.PHONY: fmt
+fmt: jsonnet-fmt markdownfmt
 
-	promtool check rules prometheus-alerts.yaml
+.PHONY: jsonnet-fmt
+jsonnet-fmt: $(JSONNETFMT_BIN)
+	@find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
+		xargs -n 1 -- $(JSONNETFMT_BIN) $(JSONNETFMT_ARGS) -i
 
-test: prometheus-alerts.yaml
-	promtool test rules tests.yaml
+.PHONY: markdownfmt
+markdownfmt: $(MARKDOWNFMT_BIN)
+	@for file in $(MD_FILES); do $(MARKDOWNFMT_BIN) -w -gofmt $$file; done
 
+prometheus_alerts.yaml: $(JSONNET_BIN) mixin.libsonnet lib/alerts.jsonnet alerts/*.libsonnet
+	@$(JSONNET_BIN) -J vendor -S lib/alerts.jsonnet > $@
+
+prometheus_rules.yaml: $(JSONNET_BIN) mixin.libsonnet lib/rules.jsonnet rules/*.libsonnet
+	@$(JSONNET_BIN) -J vendor -S lib/rules.jsonnet > $@
+
+$(OUT_DIR): $(JSONNET_BIN) $(JSONNET_VENDOR) mixin.libsonnet lib/dashboards.jsonnet $(SRC_DIR)/*.libsonnet
+	@mkdir -p $(OUT_DIR)
+	@$(JSONNET_BIN) -J vendor -m $(OUT_DIR) lib/dashboards.jsonnet
+
+.PHONY: lint
+lint: jsonnet-lint alerts-lint dashboards-lint vale pint-lint
+
+.PHONY: jsonnet-lint
+jsonnet-lint: $(JSONNETLINT_BIN) $(JSONNET_VENDOR)
+	@find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
+		xargs -n 1 -- $(JSONNETLINT_BIN) -J vendor
+
+.PHONY: alerts-lint
+alerts-lint: $(PROMTOOL_BIN) prometheus_alerts.yaml prometheus_rules.yaml
+	@$(PROMTOOL_BIN) check rules prometheus_rules.yaml
+	@$(PROMTOOL_BIN) check rules prometheus_alerts.yaml
+
+$(OUT_DIR)/.lint: $(OUT_DIR)
+	@cp .lint $@
+
+.PHONY: dashboards-lint
+dashboards-lint: $(GRAFANA_DASHBOARD_LINTER_BIN) $(OUT_DIR)/.lint
+	# Replace $$interval:$$resolution var with $$__rate_interval to make dashboard-linter happy.
+	@sed -i -e 's/$$interval:$$resolution/$$__rate_interval/g' $(OUT_DIR)/*.json
+	@find $(OUT_DIR) -name '*.json' ! -name 'celery-tasks.json' -print0 | xargs -n 1 -0 $(GRAFANA_DASHBOARD_LINTER_BIN) lint --strict
+
+.PHONY: vale
+vale: $(VALE_BIN)
+	@$(VALE_BIN) sync && \
+		$(VALE_BIN) $(MD_FILES)
+
+.PHONY: pint-lint
+pint-lint: generate $(PINT_BIN)
+	@# Pint will not exit with a non-zero status code if there are linting issues.
+	@output=$$($(PINT_BIN) -n -o -l WARN lint prometheus_alerts.yaml prometheus_rules.yaml 2>&1); \
+	if [ -n "$$output" ]; then \
+		echo "\n$$output"; \
+		exit 1; \
+	fi
+
+.PHONY: clean
 clean:
-	rm -rf dashboards_out prometheus-alerts.yaml
+	# Remove all files and directories ignored by git.
+	git clean -Xfd .
+
+.PHONY: test
+test: $(PROMTOOL_BIN) prometheus_alerts.yaml prometheus_rules.yaml
+	@$(PROMTOOL_BIN) test rules tests/*.yaml
+
+$(BIN_DIR):
+	mkdir -p $(BIN_DIR)
+
+$(TOOLING): $(BIN_DIR)
+	@echo Installing tools from hack/tools.go
+	@cd scripts && go list -e -mod=mod -tags tools -f '{{ range .Imports }}{{ printf "%s\n" .}}{{end}}' ./ | xargs -tI % go build -mod=mod -o $(BIN_DIR) %
